### ISSUE TITLE
Not compatible with laravel ^11.3.1

### ISSUE THREAD

**Issue by tansautn** [nova-horizons/realoquent#123]
### Realoquent Version

0.4.0

### Laravel Version

11.3.1

### PHP Version

8.2

### Operating System & Version

Windows 10 Build 19045

### Database Type & Version

MySQL 5.7.33x64 windows

### Description

**Step to reproduce**

+ Install clean laravel with `composer create-project`
+ Setup .env
+ add `"roave/security-advisories" : "dev-latest",` to composer.json
+ run `composer update`.
+ Run `composer require --dev nova-horizons/realoquent`.

The problem is just dependency version miss match. The `nikic/php-parser` in my project is locked to 5.0.2 but `realoquent` require which one `^4.18.0`.

Here is screenshot. See for more detail
![phpstorm64_2024-04-13_19-19-15](https://github.com/nova-horizons/realoquent/assets/6666271/cb1b3cb1-a19f-47da-bd9d-0df365848c0e)

**Comment by tansautn** [comment]
Close cuz i saw #108.

**Comment by pb30** [comment]
Just published v0.5.0, give that a try

**Comment by tansautn** [comment]
> Just published v0.5.0, give that a try

just see the pull. i known it's will work ;)
